version: '3.9'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" #API
      - "9001:9001" #WEB CONSOLE
    volumes:
      - ./docs:/data
    env_file:
      - ../.env
    command: server /data --console-address ":9001"
    restart: unless-stopped