spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://localhost:5555/ishoppingorders
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: ishopping-update-order
      auto-offset-reset: earliest

server:
  port: 8080

ishopping:
  orders:
    clients:
      products:
        url: 'http://localhost:8081/products'
      clients:
        url: 'http://localhost:8082/clients'

  config:
    kafka:
      server-url: 'http://localhost:29092'
      topics:
        orders-paid: 'ishopping.orders-paid'
        orders-invoiced: 'ishopping.orders-invoiced'
        orders-shipped: 'ishopping.orders-shipped'