spring:
  application:
    name: logistic
  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: ishopping-logistic
      auto-offset-reset: earliest

server:
  port: 8084

ishopping:
  config:
    kafka:
      topics:
        orders-invoiced: 'ishopping.orders-invoiced'
        orders-shipped: 'ishopping.orders-shipped'