spring:
  application:
    name: invoicing
  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: ishopping-invoice
      auto-offset-reset: earliest

ishopping:
  config:
    kafka:
      topics:
        orders-paid: 'ishopping.orders-paid'
        orders-invoiced: 'ishopping.orders-invoiced'

server:
  port: 8083

minio:
  url: 'http://localhost:9000'
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: ishopping.invoices
